### ISSUE TITLE
HProgressBar don't work.

### ISSUE THREAD

**Issue by condo4** [linknx/knxweb#11]
VProgressbar works (but backwards), but hprogressbar don't work at all...

Issue is strange, JS code seem to be good in widget folder (change width attribut), but in chrome inspector, the properties change by CHProgressBar.prototype.updateObject is HEIGHT :

// Called by eibcommunicator when a feedback object value has changed
CHProgressBar.prototype.updateObject = function(obj,value) {

	if (obj==this.conf.getAttribute("feedback-object"))
	{
			if (!this.conf.getAttribute("feedback-type") || this.conf.getAttribute("feedback-type") == "5.001") $('.bar', this.div).css('height', Math.round(value) + '%');
			else if (this.conf.getAttribute("feedback-type") == "5.003") $('.bar', this.div).css('height', (Math.round(value) * 100 / 360) + '%');
	}
};

I look for the root cause, but I can't understand...

**Comment by energy01** [comment]
#Hi,
thanks for the bug and the Pull but you not resolve the bug with it you make another one with an css width an not height

i push to fixed it : 4d3f64e20ca0401c2b2dc7a83b2a7f3ce149a771

thanks a lot
Anthony.
